const MODULES=[
'Attentional Control / Coherence','Attentional Control / Open Awareness','Gap Access','Elevated Emotion / State Generation','Intention / New Potentials','Embodiment / State Interruption','Energy Centers','OBE Foundation / Focus 10','OBE Induction / Separation','Remote Viewing Foundation','Advanced Remote Viewing','Psionics Foundation','Psionics Development','Intuition / Dreams / Creative Reception','Group Intention / Collective Practice','Integration / Living in the Field'];
const DAYS=Array.from({length:112},(_,i)=>({day:i+1,week:Math.floor(i/7)+1,module:MODULES[Math.floor(i/7)],authored:i===0}));
const day1Lesson=`Day 1 trains state control. The goal is not to produce an unusual experience. You are learning four controls: physical settling, heart-centered coherence, deliberate narrow attention, and widened spatial awareness. You will notice that attention can be placed, captured, recovered, and broadened. The morning practice lasts 25 minutes: 3 minutes settling, 5 minutes coherence, 5 minutes breath attention, 10 minutes open-focus spatial awareness, and 2 minutes pure observation. During coherence, use a real memory to generate appreciation, then release the memory while retaining the emotional state. During breath attention, count complete breath cycles to ten and restart at one whenever you notice that attention wandered. During open focus, move from awareness of the volume inside the head to the space surrounding the head, chest, abdomen, whole body, room, and finally the entire auditory field. The final two minutes contain no technique: just awareness. Today passes if you complete the practice, catch at least one attentional capture, and complete at least three daytime micro-entries.`;
const day1Prompts=[
['starting','Starting state: tired, busy, calm, irritated, excited, or something else?'],
['relax','Physical relaxation before and after, 0–5. What changed?'],
['coherence','Coherence shift, 0–5. What memory most easily produced appreciation?'],
['retain','Could you retain the emotion after dropping the memory? Describe.'],
['count','Longest breath count before distraction, and most common distraction.'],
['open','Open-focus depth, 0–5. Did body boundaries, time sense, or internal narration change?'],
['moment','Most interesting moment of the session.'],
['question','One question you now have. Do not force an answer today.'],
['micro','How many daytime micro-entries did you complete? What did you notice?'],
['evening','Evening: strongest emotional reaction today, and did you notice it before acting from it?']
];
const guided=[
 {p:'Physical Settling',t:'Sit upright. Close your eyes. Let the jaw, tongue, shoulders, chest, abdomen, hands, pelvis, legs, and feet release unnecessary tension. Do not force relaxation; notice contraction and allow a small release on each exhale.',s:35},
 {p:'Physical Settling',t:'Continue the body scan quietly. If you find tension, feel it accurately rather than fighting it.',s:70},
 {p:'Physical Settling',t:'Let the body become slightly heavier and less ready to do something.',s:75},
 {p:'Coherence',t:'Bring attention to the center of the chest. Breathe a little slower, comfortably, as though the breath moves through the chest.',s:45},
 {p:'Coherence',t:'Recall one specific memory that produces genuine appreciation. Use the memory only long enough to generate the feeling.',s:60},
 {p:'Coherence',t:'Now release the memory and try to keep the feeling itself. If it fades, briefly use the memory again, then release it.',s:90},
 {p:'Coherence',t:'Remain with the physical-emotional signature of appreciation. Let the body learn the state without needing the story.',s:105},
 {p:'Single-Point Attention',t:'Release the emotional exercise. Bring attention to the sensation of breathing at the nostrils. Count complete breath cycles from one to ten. If attention wanders, restart at one without frustration.',s:120},
 {p:'Single-Point Attention',t:'Continue counting. The repetition is noticing capture and deliberately returning attention.',s:120},
 {p:'Single-Point Attention',t:'For the final minute, notice whether there is a tiny moment between a thought beginning and your decision to follow it.',s:60},
 {p:'Open Focus',t:'Stop counting. Become aware of the three-dimensional volume inside your head, behind the eyes and from ear to ear.',s:60},
 {p:'Open Focus',t:'Expand awareness to the space immediately surrounding the head. Do not visualize an object; become aware of volume and space.',s:70},
 {p:'Open Focus',t:'Move awareness to the chest as a volume, then the space around the chest.',s:70},
 {p:'Open Focus',t:'Become aware of abdomen and pelvis as one volume, then the space surrounding them.',s:70},
 {p:'Open Focus',t:'Feel the entire body simultaneously as one three-dimensional volume occupying space.',s:70},
 {p:'Open Focus',t:'Expand awareness six inches, then one foot, then several feet around the body. Let awareness include the space rather than remaining only inside the head.',s:90},
 {p:'Open Focus',t:'Become aware of the entire room at once. Avoid naming objects. Experience the volume of the room.',s:80},
 {p:'Open Focus',t:'Notice the farthest sound, then the nearest sound, then allow all sounds to exist inside one auditory field.',s:90},
 {p:'Open Focus',t:'If thoughts arise, let them be events inside the same larger field. Do not push them away.',s:100},
 {p:'Pure Observation',t:'Release every technique now. No breath control, counting, visualization, or effort. Simply notice thoughts, sounds, sensations, and breathing.',s:60},
 {p:'Pure Observation',t:'Ask once, silently: What is aware of all of this? Do not answer. Rest as awareness.',s:45},
 {p:'Return',t:'Take a slightly deeper breath. Feel the chair and your feet. Open your eyes slowly and keep a little of the spacious awareness as you return.',s:15}
];
const lightIdx=new Set([0,3,7,10,14,17,19,20,21]);
const minimalIdx=new Set([0,3,7,10,19,21]);
const state=JSON.parse(localStorage.getItem('qctp-state')||'null')||{currentDay:1,done:{},answers:{},logs:[],settings:{mode:'guided',rate:.92,volume:1,tone:.35,timing:false,voice:''},test:false};
function save(){localStorage.setItem('qctp-state',JSON.stringify(state));}
function fmt(sec){sec=Math.max(0,Math.round(sec));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function nav(){return `<div class="nav"><div class="navin">${[['today','Today'],['lesson','Lesson'],['practice','Practice'],['workbook','Workbook'],['progress','Progress'],['logs','Logs']].map(([k,n])=>`<button data-nav="${k}" class="${view===k?'active':''}">${n}</button>`).join('')}</div></div>`}
let view='today';let runner=null;
function header(){let d=DAYS[state.currentDay-1];return `<div class="top"><div class="brand">QCTP</div><div class="daypill">Day ${d.day} · Week ${d.week}</div></div>`}
function render(){if(runner&&view!=='practice')stopRunner(false);const app=document.querySelector('#app');app.innerHTML=`<main class="shell">${header()}${screen()}</main>${nav()}`;bind();}
function screen(){return ({today:todayScreen,lesson:lessonScreen,practice:practiceScreen,workbook:workbookScreen,progress:progressScreen,logs:logsScreen}[view])()}
function todayScreen(){let d=DAYS[state.currentDay-1], done=state.done[d.day]||{};return `<section class="card hero"><div class="kicker">${d.module}</div><h1>Day ${d.day}</h1><p class="muted">${d.authored?'Fully authored session':'Curriculum slot reserved. Detailed lesson not yet authored.'}</p>${d.day===1?`<div class="row"><div class="metric"><span class="muted">Morning</span><b>25 min</b></div><div class="metric"><span class="muted">Mode</span><b>${cap(state.settings.mode)}</b></div></div><button class="bigbtn" id="begin">Begin Today</button>`:`<div class="safe">Day ${d.day} is intentionally not fabricated yet. The course structure is wired, but only Day 1 is released in this build.</div>`}</section><section class="card"><h2>Today’s components</h2>${['morning','midday','evening'].map(k=>`<div class="toggle"><span>${cap(k)}</span><button class="smallbtn mark" data-part="${k}">${done[k]?'Completed':'Mark complete'}</button></div>`).join('')}</section><section class="card"><h2>Phone-first morning flow</h2><p class="lessonp">Open QCTP, tap <b>Begin Today</b>, put the phone face-down, and let the sequencer handle spoken cues and real silence automatically. Do not branch into unrelated scrolling before the core practice ends.</p></section><section class="card installhint"><b>Install on iPhone:</b> open this site in Safari, Share → Add to Home Screen.</section>`}
function lessonScreen(){let d=DAYS[state.currentDay-1];return `<section class="card"><div class="kicker">Day ${d.day} lesson</div><h1>${d.module}</h1>${d.day===1?`<p class="lessonp">${day1Lesson}</p><button class="bigbtn secondary" id="speakLesson">Listen to lesson</button>`:`<div class="safe">This day is structurally reserved but not yet authored. The app will not invent detailed content.</div>`}</section>`}
function practiceScreen(){let d=DAYS[state.currentDay-1];if(d.day!==1)return `<section class="card"><div class="safe">Guided practice for this day is not authored yet.</div></section>`;return `<section class="card"><div class="kicker">Guided Practice</div><h1>Day 1 · 25 minutes</h1><div class="cuebox"><div class="phase" id="phase">Ready</div><div class="cue" id="cue">Tap Start. Put the phone down. Spoken cues will be separated by real silence.</div><div class="timer mono" id="timer">25:00</div></div><div class="timeline"><div id="bar"></div></div><div class="controls"><button id="restart">Restart</button><button id="play">Start</button><button id="skip">Skip cue</button></div><div class="row" style="margin-top:10px"><button class="smallbtn" id="mode">${cap(state.settings.mode)}</button><button class="smallbtn" id="test">Test mode: ${state.test?'ON':'OFF'}</button></div><p class="footerhint">Test mode compresses silence intervals so the full sequencer can be verified quickly. Real mode preserves the intended 25-minute session.</p></section>`}
function workbookScreen(){let a=state.answers[1]||{};return `<section class="card"><div class="kicker">Day 1 Workbook</div><h1>Reflection & calibration</h1>${day1Prompts.map(([id,q])=>`<div class="prompt"><label>${q}</label><textarea data-answer="${id}">${esc(a[id]||'')}</textarea></div>`).join('')}<button class="bigbtn" id="saveAnswers">Save workbook</button></section>`}
function progressScreen(){return `<section class="card"><div class="kicker">112-day curriculum</div><h1>Progress</h1><p class="muted">Course state advances by completed day, not by calendar date.</p>${MODULES.map((m,i)=>{let start=i*7+1,end=start+6,cur=state.currentDay;return `<div class="week ${cur>end?'done':''}"><b>Week ${i+1}</b><div>${m}</div><div class="muted">Days ${start}–${end}</div></div>`}).join('')}<div class="row"><button class="smallbtn" id="export">Export JSON</button><label class="smallbtn" style="text-align:center">Import JSON<input id="import" type="file" accept="application/json" style="display:none"></label></div></section>`}
function logsScreen(){return `<section class="card"><div class="kicker">Explore / Logs</div><h1>Structured future modules</h1><p class="muted">These logs are available now even though advanced lessons are not yet released.</p>${['OBE / Focus 10','Remote Viewing','Psionics','Dream / Synchronicity','Intuition / Reception'].map((n,i)=>`<div class="week"><b>${n}</b><textarea class="logtext" data-log="${i}" placeholder="Record observations, session conditions, impressions, feedback, or results..."></textarea><button class="smallbtn addlog" data-log="${i}">Save entry</button></div>`).join('')}</section><section class="card"><h2>Settings</h2><label>Guidance mode<select id="setMode"><option value="guided">Guided</option><option value="light">Light Guidance</option><option value="minimal">Minimal</option></select></label><label>Speech rate<input id="rate" type="range" min="0.7" max="1.15" step="0.01" value="${state.settings.rate}"></label><label>Voice volume<input id="vol" type="range" min="0" max="1" step="0.05" value="${state.settings.volume}"></label><label>Tone volume<input id="tone" type="range" min="0" max="1" step="0.05" value="${state.settings.tone}"></label><div class="safe">Altered-state practices are never suitable while driving, operating machinery, on ladders, in water, or anywhere loss of ordinary task attention could be dangerous.</div></section>`}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;render()});let el;
 if(el=document.querySelector('#begin'))el.onclick=()=>{view='lesson';render();setTimeout(()=>document.querySelector('#speakLesson')?.click(),250)};
 if(el=document.querySelector('#speakLesson'))el.onclick=()=>{speak(day1Lesson,()=>{view='practice';render()})};
 document.querySelectorAll('.mark').forEach(b=>b.onclick=()=>{state.done[1]=state.done[1]||{};state.done[1][b.dataset.part]=true;if(b.dataset.part==='evening'&&state.currentDay===1){state.currentDay=2}save();render()});
 if(el=document.querySelector('#play'))el.onclick=toggleRunner;if(el=document.querySelector('#restart'))el.onclick=()=>startRunner(true);if(el=document.querySelector('#skip'))el.onclick=skipCue;if(el=document.querySelector('#mode'))el.onclick=()=>{state.settings.mode=state.settings.mode==='guided'?'light':state.settings.mode==='light'?'minimal':'guided';save();render()};if(el=document.querySelector('#test'))el.onclick=()=>{state.test=!state.test;save();render()};
 if(el=document.querySelector('#saveAnswers'))el.onclick=()=>{state.answers[1]=state.answers[1]||{};document.querySelectorAll('[data-answer]').forEach(t=>state.answers[1][t.dataset.answer]=t.value);save();el.textContent='Saved';};
 if(el=document.querySelector('#export'))el.onclick=exportData;if(el=document.querySelector('#import'))el.onchange=importData;
 document.querySelectorAll('.addlog').forEach(b=>b.onclick=()=>{let t=document.querySelector(`.logtext[data-log="${b.dataset.log}"]`);state.logs.push({type:b.dataset.log,day:state.currentDay,ts:new Date().toISOString(),text:t.value});t.value='';save();b.textContent='Saved'});
 if(el=document.querySelector('#setMode')){el.value=state.settings.mode;el.onchange=()=>{state.settings.mode=el.value;save()}}if(el=document.querySelector('#rate'))el.oninput=()=>{state.settings.rate=+el.value;save()};if(el=document.querySelector('#vol'))el.oninput=()=>{state.settings.volume=+el.value;save()};if(el=document.querySelector('#tone'))el.oninput=()=>{state.settings.tone=+el.value;save()};}
function cap(s){return s.replace(/\b\w/g,c=>c.toUpperCase())}function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function speak(text,done){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.rate=state.settings.rate;u.volume=state.settings.volume;let voices=speechSynthesis.getVoices();if(state.settings.voice){let v=voices.find(v=>v.name===state.settings.voice);if(v)u.voice=v}u.onend=()=>done&&done();speechSynthesis.speak(u)}
function tone(){try{let A=window.AudioContext||window.webkitAudioContext,ctx=new A(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=523.25;g.gain.value=state.settings.tone*.12;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.6);o.stop(ctx.currentTime+.62)}catch(e){}}
function seq(){let arr=guided.map((x,i)=>({...x,i}));if(state.settings.mode==='light')arr=arr.filter(x=>lightIdx.has(x.i));if(state.settings.mode==='minimal')arr=arr.filter(x=>minimalIdx.has(x.i));return arr}
function fullDuration(){return guided.reduce((a,b)=>a+b.s,0)}
function startRunner(force=false){stopRunner(false);let list=seq(), idx=0, elapsed=0, total=fullDuration(), start=Date.now(), paused=false, left=0;runner={list,idx,elapsed,total,start,paused,left,timer:null,timeout:null};document.querySelector('#play').textContent='Pause';runCurrent();runner.timer=setInterval(()=>{if(!runner||runner.paused)return;let e=(Date.now()-runner.start)/1000+runner.elapsed, remain=Math.max(0,total-e);document.querySelector('#timer').textContent=fmt(remain);document.querySelector('#bar').style.width=`${Math.min(100,(e/total)*100)}%`},250)}
function runCurrent(){if(!runner)return;if(runner.idx>=runner.list.length){finishRunner();return}let x=runner.list[runner.idx], cue=document.querySelector('#cue'),phase=document.querySelector('#phase');if(!cue)return;phase.textContent=x.p;cue.textContent=x.t;tone();speak(x.t,()=>{let delay=(state.test?Math.min(6,Math.max(2,x.s/20)):x.s)*1000;runner.timeout=setTimeout(()=>{runner.elapsed+=(state.test?Math.min(6,Math.max(2,x.s/20)):x.s);runner.start=Date.now();runner.idx++;runCurrent()},delay)})}
function toggleRunner(){if(!runner){startRunner();return}if(runner.paused){runner.paused=false;runner.start=Date.now();document.querySelector('#play').textContent='Pause';runCurrent()}else{runner.paused=true;clearTimeout(runner.timeout);speechSynthesis.cancel();document.querySelector('#play').textContent='Resume'}}
function skipCue(){if(!runner)return;clearTimeout(runner.timeout);speechSynthesis.cancel();runner.idx++;runner.start=Date.now();runCurrent()}
function stopRunner(clear=true){if(!runner)return;clearInterval(runner.timer);clearTimeout(runner.timeout);speechSynthesis.cancel();runner=null}
function finishRunner(){tone();stopRunner(false);let cue=document.querySelector('#cue'),phase=document.querySelector('#phase'),timer=document.querySelector('#timer'),bar=document.querySelector('#bar');if(cue){phase.textContent='Complete';cue.textContent='Day 1 morning practice complete. Remain still for a few seconds, then open the Workbook when you are ready.';timer.textContent='0:00';bar.style.width='100%';document.querySelector('#play').textContent='Done';state.done[1]=state.done[1]||{};state.done[1].morning=true;save()}}
function exportData(){let b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='QCTP_training_data.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{Object.assign(state,JSON.parse(r.result));save();render()}catch(err){alert('Invalid QCTP JSON')}};r.readAsText(f)}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
